"""initial

Revision ID: e10601b3a938
Revises: 
Create Date: 2026-03-05 16:23:07.293186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10601b3a938'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='faol', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('week_type', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('lesson_type', sa.String(), nullable=True),
    sa.CheckConstraint("week_type IN ('odd', 'even') OR week_type IS NULL", name='ck_week_type_values'),
    sa.CheckConstraint('lesson_number BETWEEN 1 AND 6', name='ck_lesson_number_range'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'day_of_week', 'lesson_number', 'week_type', name='uq_group_slot'),
    sa.UniqueConstraint('room_id', 'day_of_week', 'lesson_number', 'week_type', name='uq_room_slot'),
    sa.UniqueConstraint('teacher_id', 'day_of_week', 'lesson_number', 'week_type', name='uq_teacher_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('teachers')
    op.drop_table('rooms')
    op.drop_table('groups')
    # ### end Alembic commands ###
